# Configure main menu and social menu
[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/jiangyigithub"

[social.params]
icon = "brand-github"

[[social]]
identifier = "scholar"
name = "Google Scholar"
url = "https://scholar.google.com/citations?user=BaqGkQQAAAAJ"

[social.params]
icon = "googlescholar"

[[social]]
identifier = "bilibili"
name = "bilibili"
url = "https://space.bilibili.com/26251043"

[social.params]
icon = "bilibili"