# Configure main menu and social menu
[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/jiangyigithub"

[social.params]
icon = "brand-github"

[[social]]
identifier = "scholar"
name = "zhihu"
url = "https://www.zhihu.com/people/SuAReZENSport"

[social.params]
icon = "googlescholar"

[[social]]
identifier = "bilibili"
name = "bilibili"
url = "https://space.bilibili.com/26251043"

[social.params]
icon = "bilibili"